version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: capitaisDoBrasil
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: ./NodeApp
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build: ./PHPApp
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  db_data:
